site_name: Formation Python
site_url: https://souleymanediallo.github.io/
site_author: Souleymane Diallo
copyright: Copyright &copy; 2024 ACADEMY221

theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  name: material
  language: fr
  features:
    - navigation.top
    - navigation.indexes
    - search.share
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg # Pluging

plugins:
  - search:
      lang: fr
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocs-video
  - blog:
      blog_dir: blog
      archive_date_format: yyyy
      authors_profiles_toc: true
      pagination_per_page: 5
      pagination_format: "~2~"
      authors_profiles_toc: true
 

  # - tags:
  #     tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower
      
